### ISSUE TITLE
Illegal wire type for field Message.Field .ResponseEnvelop.CaptureAward.ActivityType: 2 (0 expected)

### ISSUE THREAD

**Issue by brettstack** [Armax/Pokemon-GO-node-api#126]
I'm getting the following error sometimes when attempting to catch a pokemon (usually the first or second pokemon, may be related to the first location I scan). Other pokemon result in an immediate flee (soft ban), any ideas?

```
Error: Illegal wire type for field Message.Field .ResponseEnvelop.CaptureAward.ActivityType: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:3233:48)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Users/brett/Projects/pokemon-go/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Users/brett/Projects/pokemon-go/node_modules/pokemon-go-node-api/poke.io.js:341:81
    at Request._callback (/Users/brett/Projects/pokemon-go/node_modules/pokemon-go-node-api/poke.io.js:140:24)
    at Request.self.callback (/Users/brett/Projects/pokemon-go/node_modules/request/request.js:187:22)
```

**Comment by segura2010** [comment]
You could comment this line on pokemon.proto to avoid the problem:  https://github.com/Armax/Pokemon-GO-node-api/blob/master/pokemon.proto#L930

**Comment by brettstack** [comment]
Thanks. Do you knows the reason for it though? I don't want to patch this
if it's not going to be in master here

**Comment by Armax** [comment]
I'm currently working on this hope to fix it soon
