### ISSUE TITLE
NEW: Error: Error

### ISSUE THREAD

**Issue by reecube** [Armax/Pokemon-GO-node-api#134]
Yesterday the api worked fine, today it isn't anymore. I always get the following error:

```
Error: Error
    at Request._callback (***\node_modules\pokemon-go-node-api\poke.io.js:128:25)
    at self.callback (***\node_modules\request\request.js:187:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (***\node_modules\request\request.js:813:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
```

It seems like PTC is offline: https://club.pokemon.com/us/pokemon-trainer-club/
Also PokeVision is offline: https://pokevision.com/

Could it be possible that they changed the api to destroy all these 3rd party projects? Do you guys have the same issues as me? Could we fix it and if yes, how?

**Comment by gallexme** [comment]
no just pokemon servers crashed/overloaded

**Comment by Armax** [comment]
as @gallexme said, pokemon's servers are offline
