### ISSUE TITLE
Error: Illegal value for [object Object] of type double: string (not a number)

### ISSUE THREAD

**Issue by jch254** [Armax/Pokemon-GO-node-api#136]
Getting this error while trying to run. Looks like the self.init method is failing calling self.GetApiEndpoint at line 172

2016-07-26T02:48:29.336Z    6dc39be9-52db-11e6-bf04-1b7f678fa4e2    Error: Illegal value for [object Object] of type double: string (not a number) at Error (native) at fail (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1801:23) at ProtoBuf.Reflect.ElementPrototype.verifyValue (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1857:25) at ProtoBuf.Reflect.FieldPrototype.verifyValue (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3474:33) at MessagePrototype.set (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2475:59) at MessagePrototype.set (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2466:38) at Message (/var/task/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2395:34) at api_req (/var/task/node_modules/pokemon-go-node-api/poke.io.js:100:17) at Pokeio.self.GetApiEndpoint (/var/task/node_modules/pokemon-go-node-api/poke.io.js:210:5) at /var/task/node_modules/pokemon-go-node-api/poke.io.js:172:14

**Comment by jch254** [comment]
Closing as this was my own error in using the package, I was using strings instead of numbers for location values.
