### ISSUE TITLE
Geocoder returning undefined on name lookup

### ISSUE THREAD

**Issue by FunkeDope** [Armax/Pokemon-GO-node-api#145]
This was working fine for me the other day, but now I can't seem to run even the example using a "name" location. 

I'm getting the following error:

``` javascript
/home/kyle/web/Pokemon-GO-node-api/poke.io.js:569
                var _data$results$0$geome = data.results[0].geometry.location;
                                                           ^

TypeError: Cannot read property 'geometry' of undefined
    at /home/kyle/web/Pokemon-GO-node-api/poke.io.js:569:60
    at Request._callback (/home/kyle/web/Pokemon-GO-node-api/node_modules/geocoder/providers/google.js:20:5)
    at Request.self.callback (/home/kyle/web/Pokemon-GO-node-api/node_modules/geocoder/node_modules/request/main.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/kyle/web/Pokemon-GO-node-api/node_modules/geocoder/node_modules/request/main.js:654:16)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/kyle/web/Pokemon-GO-node-api/node_modules/geocoder/node_modules/request/main.js:616:14)
    at emitNone (events.js:91:20)
```

**Comment by FunkeDope** [comment]
This just fixed itself...so I have no idea what happened...
