### ISSUE TITLE
Error: RPC server offline

### ISSUE THREAD

**Issue by aidenwallis** [Armax/Pokemon-GO-node-api#18]
So I am using my own username/password for pokemon.com and this is what I'm getting (I am using ptc):
`
[i] Logging with user: USERNAME HERE
[i] Session token: TGT-6020617-5fH4qoXceS-TOKENSTUFF-htO0Bjg-sso.pokemon.com
[!] RPC Server offline
/Users/aiden/DEV/pokemongo-test/routes/index.js:26
    if (err) throw err;
             ^

Error: RPC Server offline
    at Request._callback (/Users/aiden/DEV/pokemongo-test/node_modules/pokemon-go-node-api/poke.io.js:88:33)
    at self.callback (/Users/aiden/DEV/pokemongo-test/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/aiden/DEV/pokemongo-test/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
`

**Comment by Armax** [comment]
The PTC servers are offline at the moment :( it's not our fault

**Comment by aidenwallis** [comment]
Alright, I thought they were, but just wanted to make sure it wasn't on your end and it's not that it's not successfully connecting or whatever, thanks for your help :)

**Comment by Armax** [comment]
Maybe we should add a clean error instead of a stack trace :)

**Comment by aidenwallis** [comment]
That would be great if you did, and just say to anyone (as I know this library is very new, that's why I brought it up) that it's not an issue with the library, or you may get people confirming it like me :)

**Comment by aidenwallis** [comment]
I assumed it was some sort of error with you guys from the stack trace.

**Comment by Armax** [comment]
Yeah the stack trace is more like a crash instead of a remote error, I will change this in the next commit :)
