### ISSUE TITLE
Illegal buffer

### ISSUE THREAD

**Issue by bhuebschen** [Armax/Pokemon-GO-node-api#180]
https://github.com/Armax/Pokemon-GO-node-api/blob/master/poke.io.js#L228

./node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346
            throw TypeError("Illegal buffer");
            ^

TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (./node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
    at Function.Message.decode (./node_modules/protobufjs/dist/protobuf.js:2930:84)
    at ./poke.io.js:228:60
    at Request._callback (./poke.io.js:149:16)
    at Request.self.callback (./node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (./node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)

**Comment by cokeeffekt** [comment]
this seems random, either the lib isn't handling something correctly or it's a server issue.

**Comment by cokeeffekt** [comment]
more info, seems we have to deal with a request throttle now.
https://www.reddit.com/r/pokemongodev/comments/4v3twy/request_throttling/
