### ISSUE TITLE
Broken Inventory Protodef

### ISSUE THREAD

**Issue by falazar** [Armax/Pokemon-GO-node-api#193]
Apparently I cant get any inventory if my pokemon is deployed anywhere, kinda stuck if I cant get this to work
(am in the chat room to talk also)

```
 b.GetInventory(function (err, res) {
     if (err) {
         console.log("Error happened4:", err);
         return;
     }
     console.log('inventory response = ', res);
 });


/*
C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:2938
throw(e);
^

Error: Illegal wire type for field Message.Field .ResponseEnvelop.PokemonData.deployed_fort_id: 2 (0 expected)
at Error (native)
at ProtoBuf.Reflect.FieldPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3679:23)
at ProtoBuf.Reflect.MessagePrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3238:45)
at ProtoBuf.Reflect.ElementPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:2185:46)
at ProtoBuf.Reflect.FieldPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3727:33)
at ProtoBuf.Reflect.MessagePrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3238:45)
at ProtoBuf.Reflect.ElementPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:2185:46)
at ProtoBuf.Reflect.FieldPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3727:33)
at ProtoBuf.Reflect.MessagePrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:3238:45)
at ProtoBuf.Reflect.ElementPrototype.decode (C:\nodestuff\node_modules\protobufjs\dist\protobuf.js:2185:46)
*/
```

**Comment by falazar** [comment]
If you comment that line out in pokemon.prot it will run without err, but missing that data bit

//      optional int32 deployed_fort_id = 8; jdr test
