### ISSUE TITLE
[!] Inventory Error TypeError: Illegal buffer

### ISSUE THREAD

**Issue by 4N1S** [Armax/Pokemon-GO-node-api#219]
[!] Inventory Error TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (/Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
    at Function.Message.decode (/Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/protobufjs/dist/protobuf.js:2930:84)
    at /Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/pokemon-go-node-api/poke.io.js:285:58
    at Request._callback (/Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/pokemon-go-node-api/poke.io.js:199:18)
    at Request.self.callback (/Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/NiS/Desktop/travail_ETE_2016/Pokemonfarm/pokebot-ui3/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

**Comment by billyriantono** [comment]
did you implement delay on every your request ?

**Comment by 4N1S** [comment]
yes 30000ms
