### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by thomas-alrek** [Armax/Pokemon-GO-node-api#235]
I am unable to run the example.
I editet the user info for "a", and removed "b".

`$ node example.js`

``` javascript
[i] Logging with user: ******.*****@gmail.com
undefined
C:\Users\******\dev\pogo\node_modules\pokemon-go-node-api\example.js:25
    if (err) throw err;
             ^

Error: 403 error from server
    at IncomingMessage.<anonymous> (C:\Users\******\dev\pogo\node_modules\gpsoauthnode\oauth.js:61:23)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

```

**Comment by junqdu** [comment]
did you use the app password?

**Comment by maxkueng** [comment]
You might have two-factor authentication enabled.

**Comment by Sy-D** [comment]
Same problem,
2 way auth is deactivated. These are my settings. I appreciate any help.

```
var location = {
    type: 'coords',
    "coords": {
    latitude: '48.800284',
    longitude :'9.205570'
    }
};

var username =  '**********@gmail.com';
var password =  'GoogleAccPWHere';
var provider =  'google';
```

**Comment by NelsonGaldeman** [comment]
@Devilklone latitude & longitude attributes must be type "double", not string (remove quotes).

**Comment by Sy-D** [comment]
@NelsonGaldeman How stupid from me, thanks. I also put the wrong credentials in. Everything works fine now.
