### ISSUE TITLE
Error on evolving pokemon

### ISSUE THREAD

**Issue by WesVleuten** [Armax/Pokemon-GO-node-api#237]
Hi,

I'm getting this error when I try to evolve a weedle. The input was "10043245764815553917"

```
Error: Illegal wire type for field Message.Field .ResponseEnvelop.Pokemon.id: 1 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Users/wesvandervleuten/workspace/Pokemon-GO-node-api/poke.io.js:534:58
    at /Users/wesvandervleuten/workspace/Pokemon-GO-node-api/poke.io.js:287:18
    at Request._callback (/Users/wesvandervleuten/workspace/Pokemon-GO-node-api/poke.io.js:122:11)
```

**Comment by rafaelcorreiapoli** [comment]
I'm also having this error, did you find a solution?

**Comment by Syldel** [comment]
I have the same problem too ! Thank you for your help !

**Comment by Syldel** [comment]
Look here :
It works for me ! ;-)
https://github.com/Armax/Pokemon-GO-node-api/issues/192
Thank you !
