### ISSUE TITLE
What version of node does this support?

### ISSUE THREAD

**Issue by blackdynamo** [Armax/Pokemon-GO-node-api#26]
I am trying to use the Heartbeat and the GetPokemons calls and they are both blowing up:

```
/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346
throw TypeError("Illegal buffer");
^

TypeError: Illegal buffer
at TypeError (native)
at Function.module.exports.ByteBuffer.wrap (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
at ProtoBuf.Reflect.ElementPrototype.verifyValue (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1870:39)
at ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3474:33)
at MessagePrototype.set (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2475:59)
at Message (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2399:42)
at Pokeio.self.Heartbeat (/Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/poke.io.js:220:21)
at /Users/user/sourcecode/playground/pokemongo/pgo/index.js:36:10
at /Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/poke.io.js:123:21
at /Users/user/sourcecode/playground/pokemongo/pgo/node_modules/pokemon-go-node-api/poke.io.js:173:13
```

I am trying to wrap my head around the calls to the endpoint and once I figure that out, I could help with the project.

**Comment by Armax** [comment]
Because Heartbeat and GetPokemons are still in development, in fact are not documented

**Comment by blackdynamo** [comment]
Ya, just saw that. Sorry, should have checked closed issues first.

**Comment by Armax** [comment]
Np :)
