### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by loretoparisi** [Armax/Pokemon-GO-node-api#33]
Not sure if it's a merge or typo here

``` shell
/Pokemon-GO-node-api/poke.io.js:21
const {RequestEnvelop, ResponseEnvelop} = pokemonProto;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Pokemon-GO-node-api/example.js:3:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by WesSouza** [comment]
This is [ES6 destructuring](http://www.2ality.com/2015/01/es6-destructuring.html), if you use the stable node version (currently 6.3.0) you should not have this issue.

Also, destructuring **rocks**! 😄

**Comment by loretoparisi** [comment]
👍  I'm on node 4.4.3 that's why. Just `n 6.3.0` and now it works thanks!
