### ISSUE TITLE
Error when require.

### ISSUE THREAD

**Issue by SzymonLisowiec** [Armax/Pokemon-GO-node-api#37]
```
/var/www/node_modules/pokemon-go-node-api/poke.io.js:21
const (RequestEnvelop, ResponseEnvelop) = pokemonProto;
      ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/pokemongo/core.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by SzymonLisowiec** [comment]
Upgrade nodejs.
