### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined 

### ISSUE THREAD

**Issue by laterbreh** [Armax/Pokemon-GO-node-api#4]
Hello, 

I can't seem to get passed this part of the script, any ideas? (script is untouched, just trying to run main.js):

var ticket = r.headers['location'].split("ticket=")[1]
                                                  ^

TypeError: Cannot read property 'split' of undefined
    at Request._callback (C:\Users\Reakt\Desktop\pokego api\Pokemon-GO-node-api\logins.js:32:51)
    at Request.self.callback (C:\Users\Reakt\Desktop\pokego api\Pokemon-GO-node-api\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Reakt\Desktop\pokego api\Pokemon-GO-node-api\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Reakt\Desktop\pokego api\Pokemon-GO-node-api\node_modules\request\request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by Armax** [comment]
Are your logging in with your pokemon trainer club infos? because it can't find the access token (I still have to add checks for errors)

**Comment by laterbreh** [comment]
I was using the information that was already in there. I figured: "Arm4x","OHSHITWADDUP" is a dummy account that you were using for testing and that it would work. 

If the case is that the login information you have in Main.js is just fake information, Ill just move ahead and try and get google auth working with the script :)

**Comment by Armax** [comment]
Yeah "Arm4x","OHSHITWADDUP" is a fake credential

**Comment by Armax** [comment]
anyway if you want to add the google oauth by your own check logins.js

**Comment by Armax** [comment]
We have error handling now thanks to @jdpnielsen

**Comment by laterbreh** [comment]
I am still trying to port https://github.com/Mila432/Pokemon_Go_API/blob/master/login.py#L39 to node.js. I am having trouble with the third URL post. I have opened an issue on that Git, but I'm not sure if I am in the right direction at this point. Maybe I can send you my code snippet?

**Comment by Armax** [comment]
Yeah, join me at https://discord.gg/7Mgma private message to @Arm4x
