### ISSUE TITLE
Problem with Poke.io.js

### ISSUE THREAD

**Issue by BestCorporateEvents** [Armax/Pokemon-GO-node-api#42]
I am getting the following error when trying to run the example file. 

/node_modules/pokemon-go-node-api/poke.io.js:18
const {RequestEnvelop, ResponseEnvelop} = pokemonProto;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/User/Sites/pokemongo_node_alert/server.js:3:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

**Comment by shilch** [comment]
Ensure you have ES6 support

**Comment by havrylenkok** [comment]
Update your NodeJS to the current version.

**Comment by kyungbaekim** [comment]
I am getting the same error with latest NodeJS (4.4.7). Can anyone help?

**Comment by styfle** [comment]
@kyungbaekim Try the latest 6.3.0

**Comment by shilch** [comment]
Destructuring is not enabled for Node 4.x.x
Two Options:
1. Run the example with `--harmony-destructuring` flag
2. Update Node to the latest version (Version 6, destructuring enabled)
