### ISSUE TITLE
const {RequestEnvelop, ResponseEnvelop} = pokemonProto; 

### ISSUE THREAD

**Issue by tylern06** [Armax/Pokemon-GO-node-api#44]
Hello, 

I'm getting the following error message when I run my node server. Please let me know what type of error this is.

Thanks

const {RequestEnvelop, ResponseEnvelop} = pokemonProto;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/macbook/Desktop/MEAN/pokego_map/server/controllers/pokemons.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by tcboles** [comment]
You need to update your node. I had the same problem when running 5.3 and it is fine under 6.3
