### ISSUE TITLE
Node v6.3  return process.dlopen(module, path._makeLong(filename));

### ISSUE THREAD

**Issue by tylern06** [Armax/Pokemon-GO-node-api#46]
Hi,

After I upgraded to Node 6.3, I get the following error.  Any idea why?

return process.dlopen(module, path._makeLong(filename));
error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbook/Desktop/MEAN/pokego_map/node_modules/pokemon-go-node-api/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by arthurjdam** [comment]
Node version should be v6.2.1
Try;
`nvm install 6.2.1`
`cd node_modules/pokemon-go-node-api/`
`rm -r node_modules`
`npm install`

**Comment by Armax** [comment]
We will check and fix

**Comment by Barney16** [comment]
I have also encounter that one what am I going to do?

**Comment by fr0th** [comment]
@barney16 Use node 4.x.x for now
