### ISSUE TITLE
Error to require

### ISSUE THREAD

**Issue by samuelds** [Armax/Pokemon-GO-node-api#54]
`    let {latitude, longitude} = self.playerInfo;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/app.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by gallexme** [comment]
#52

**Comment by jonreader** [comment]
You'll get this error if your not on a new version of node.

Get **latest** rather then **recommended**.

**Comment by nicholas-c** [comment]
Getting this running `node v0.10.25` - Is this right?

**Comment by jonreader** [comment]
Without checking; I think you need version 6 or higher (6.x.x).

Current recommended is **4.4.7**, latest is **6.3.0** .

**Comment by nicholas-c** [comment]
:| How is my node version so out of date!!! I'll update and report back...

**Comment by Armax** [comment]
We removed all the ES6 stuff try now
