### ISSUE TITLE
Unable to get profile

### ISSUE THREAD

**Issue by senthilsivanath** [Armax/Pokemon-GO-node-api#65]
TypeError: Cannot read property 'Requests' of undefined
    at Pokeio.self.GetApiEndpoint (/Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/pokemon-go-node-api/poke.io.js:192:38)
    at /Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/pokemon-go-node-api/poke.io.js:156:22
    at /Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/pokemon-go-node-api/poke.io.js:186:17
    at /Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/pokemon-go-node-api/logins.js:101:21
    at /Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/gpsoauthnode/oauth.js:115:9
    at IncomingMessage.<anonymous> (/Users/senthilsivanath/Downloads/protoc-3.0.0-beta-3.1-osx-x86_64/node_modules/gpsoauthnode/oauth.js:75:49)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)

**Comment by senthilsivanath** [comment]
Had a diff Pokemon.proto in my directory. Deleted my file and the issue got resolved.
